###

POST http://localhost:4000/getNFT HTTP/1.1
content-type: application/json

{
    "network_config": {
         "network": "Mainnet"
     },
    "mint": "5sBSVRukKzpLVTJqBWDSHZiByM89RAsV5k4H8uvitLRN"
}